#!/usr/bin/env bash

if [[ -z "$EDITOR" ]]; then
  EDITOR="vi"
fi

if [[ -z "$EDITOR_WRAPPER" ]]; then
  EDITOR_WRAPPER="$EDITOR"
fi

# bash wizardry that basically just sets the delimeter to underscore to make my life not living regex hell :), ik it's probably infinitely borked but idgaf
IFS="_"; name="$*"; unset IFS


if [[ ! -z "$name" ]]; then
  printf -v FILE '~/journal/%s.md' "$name"
else
  printf -v FILE '%(~/journal/%Y-%m-%d.md)T' -1
fi

cd "$HOME/journal"
"$EDITOR" "$FILE"
