#!/usr/bin/env bash

if [[ -z "$EDITOR" ]]; then
  EDITOR="vi"
fi

# bash wizardry that basically just sets the delimeter to underscore to make my life not living regex hell :), ik it's probably infinitely borked but idgaf
IFS="_"; name="$*"; unset IFS

if [[ ! -z "$name" ]]; then
  printf -v FILE '%s/journal/math/%s/note.typst' "$HOME" "$name"
else
  printf -v FILE '%s/%(journal/math/%Y/%m/%d/note.typst)T' "$HOME"
fi

editor-typst "$FILE"
